apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      labels:
        app: edge-service
    spec:
      containers:
        - name: edge-service
          image: edge-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka/"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: edge-service
spec:
  type: NodePort
  selector:
    app: edge-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30002  # Make sure 30002 is available
